---
# Specifies the version of the Docker Compose file format
version: '3.4'

services:
  # Defines the Weaviate service
  weaviate:
    # Overrides the default command for the service
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    # Specifies the Docker image to use
    image: semitechnologies/weaviate:1.22.3
    # Maps host and container ports
    ports:
    - 8080:8080
    - 50051:50051
    # Mounts a volume to persist data across container restarts
    volumes:
    - weaviate_data:/var/lib/weaviate
    # Configures the restart policy for the service
    restart: on-failure:0
    # Sets environment variables for the service
    environment:
      COHERE_APIKEY: $COHERE_APIKEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-cohere'
      ENABLE_MODULES: 'text2vec-cohere,generative-cohere,reranker-cohere'
      CLUSTER_HOSTNAME: 'node1'

# Defines a named volume for Weaviate data persistence
volumes:
  weaviate_data:
...
