---
# Specifies the version of the Docker Compose file format
version: '3.4'

services:
  # Defines the Weaviate service
  weaviate:
    command:  # Configuration for the command to run when the container starts
    - --host
    - 0.0.0.0
    - --port
    - '808
