# This is a Docker Compose file, version 3.4

# Define a volume to store Weaviate data
volumes:
  weaviate_data:

# Define the Weaviate service
services:
  weaviate:
    # The command to start Weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '808
